title: AmwNLTL Blog
email: AmwNLTL@proton.me
tagline: Just a blog of mine
description: >
  Just some texts about me doing some reverse engineering, 
  Windows Kernel stuff 
  and other freak related topics I want to cover to help a stranger.
baseurl: ""
url: "https://amwnltl.github.io"
twitter_username: AmwNLTL
twitter:
  username: AmwNLTL
  card: summary
github_username:  AmwNLTL
social:
  name: AmwNLTL
  links:
    - https://twitter.com/AmwNLTL
    - https://github.com/AmwNLTL
permalink: /:title

author:
  name: "AmwNLTL"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-include-cache

kramdown:
  syntax_highlighter_opts:
    disable : true

exclude:
